#连接池的配置信息,如果使用druid-starter，舍弃该配置
ali:
  druid:
    driver-class-name: com.mysql.jdbc.Driver
    db-url: jdbc:mysql://localhost:3306/fileyunpan
    username: root
    password: 123456
    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    #配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
#自定义HelloWorld
com:
  szxy:
    name: hello
    password: world
  yml:
    test:
      name: hello
      age: 20
      html-locations:
        - classpath:templates/**/*.html
        - classpath:mappers/**/*.xml
      boss: true
      birth: 1999/05/20
      maps: {hello: hello, world: world}
      lists: 111,222,333
      dog:
        name: tom
        age: 2
      strmaps:
        defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
        dz:
          - 123
          - 456